swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User transactions
      summary: User bank transaction of the month
      description: API for fetching the user transaction of the month
      parameters:
      produces:
        - application/json
      responses:
        "200":
          description: User month transaction retrieved successfully
          schema:
            $ref: "#/definitions/monthTransaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/{month}/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - User transactions
      summary: User bank transaction for a specific transaction
      description: API for fetching the user transaction for a specific transaction
      parameters:
        - in: path
          name: month
          description: Month of the transaction
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successfully
          schema:
            $ref: "#/definitions/UserTransaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User transactions
      summary: Delete a user transaction
      description: Delete a user transaction for a specific month and ID
      parameters:
        - in: path
          name: month
          description: Month of the transaction
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User transactions
      summary: Modify a user transaction
      description: Modify a user transaction for a specific month and ID
      parameters:
        - in: path
          name: month
          description: Month of the transaction
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction
          required: true
          type: string
        - in: body
          name: transaction
          description: Transaction object to be modified
          required: true
          schema:
            $ref: "#/definitions/UserTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction modified successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserTransaction:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        date:
          type: string
          example: "27/02/20"
        description:
          type: string
          example: "Golden Sun Bakery"
        amount:
          type: string
          example: "$8.00"
        balance:
          type: string
          example: "$298.00"
        transactionInfo:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
            transactionType:
              type: string
              example: "Electronic"
            category:
              type: string
              example: "Food"
            note:
              type: string
              example: "Iorem ipsum"
  monthTransaction:
  type: object
  items:
    type: array
    properties:
      month:
        type: string
        description: The month
      transactions:
        type: array
        items:
          type: object
          properties:
            transaction_id:
              type: string
              description: Unique identifier for the transaction
            amount:
              type: number
              description: The amount of the transaction
            description:
              type: string
              description: A description of the transaction
